/**
 * OBD-II diagnostic trouble codes (DTC), in Spanish.
 *
 * Pure TypeScript (ADR-04). The table is bundled, not fetched: a "check engine"
 * light tends to come on exactly where there is no signal, and the lookup has
 * to work offline. `dtc.es.json` is generated by `tools/build-dtc-es.mjs` from
 * the MIT-licensed mytrile/obd-trouble-codes list (see LICENSE-mytrile.txt);
 * edit the generator, not the JSON.
 *
 * The Spanish text is a deterministic glossary translation, so it is
 * understandable rather than polished; `descEn` is kept verbatim so a mechanic
 * can always see the original wording.
 */
import data from './dtc.es.json';

export type DtcSystem = 'motor' | 'carroceria' | 'chasis' | 'red';

export type Dtc = {
  code: string;
  system: DtcSystem;
  descEn: string;
  descEs: string;
  /** False for manufacturer-specific ranges, where the meaning varies by brand. */
  isGeneric: boolean;
};

type RawDtc = Omit<Dtc, 'isGeneric'> & { isGeneric: number };

const CODE_RE = /^[PBCU][0-3][0-9A-F]{3}$/;

/**
 * Accepts what people actually type or what a scanner app shows — " p0301 ",
 * "P0301" — and returns the canonical upper-case form, or null when it is not a
 * well-formed code.
 */
export function normalizeCode(input: string): string | null {
  const code = input.trim().toUpperCase();
  return CODE_RE.test(code) ? code : null;
}

/**
 * SAE J2012 marks manufacturer ranges by the second character: P1 and P3 for
 * powertrain (strictly P30–P33; all of P3 is treated as manufacturer, same as
 * the generator), and 1 or 2 for B, C and U. Works for any well-formed code, so
 * the app can say "depende de la marca" even when the table has no entry.
 */
export function isManufacturerSpecific(code: string): boolean {
  const c = normalizeCode(code);
  if (!c) return false;
  const second = c[1];
  if (c[0] === 'P') return second === '1' || second === '3';
  return second === '1' || second === '2';
}

// Built on first use: ~3,000 rows is cheap, but there is no reason to pay for
// it at app start when most sessions never look up a code.
let index: Map<string, Dtc> | null = null;

function getIndex(): Map<string, Dtc> {
  if (!index) {
    index = new Map();
    for (const row of data as RawDtc[]) {
      index.set(row.code, { ...row, isGeneric: row.isGeneric === 1 });
    }
  }
  return index;
}

export function lookup(code: string): Dtc | null {
  const c = normalizeCode(code);
  if (!c) return null;
  return getIndex().get(c) ?? null;
}

/**
 * One Spanish line for the UI. A manufacturer code missing from the table is
 * normal (every brand has its own list), so it gets a specific message instead
 * of a generic "no encontrado" that would read like the app failed.
 */
export function describe(code: string): string {
  const hit = lookup(code);
  if (hit) return hit.descEs;
  if (isManufacturerSpecific(code)) return 'Código específico del fabricante';
  return 'Código no encontrado en la tabla';
}

/** Every row, for search or listing screens. */
export function allCodes(): Dtc[] {
  return [...getIndex().values()];
}
