// Generated by tools/build-changelog.mjs from CHANGELOG.md — do not edit by hand.
// Run `node tools/build-changelog.mjs` (npm start / build do it for you).
import type { ChangelogEntry } from './changelog/parse';

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "2.2.0",
    "name": null,
    "date": null,
    "unreleased": true,
    "intro": [],
    "sections": [
      {
        "title": null,
        "intro": [],
        "items": [
          "**Litros o galones**: cada vehículo elige su unidad; los datos se guardan en litros por dentro. Tus números de siempre se ven igual.",
          "**Registrar un carro es más rápido**: marca, modelo y año de una lista (con los modelos de aquí: Hilux, Sprinter Trueno, Grand i10…), color con muestras, tipo de carrocería, varias fotos con portada, precio y fecha de compra a la vista.",
          "**Más estados**: en el taller, accidentado, en restauración, prestado… con \"desde\" y una nota.",
          "**Aceite**: viscosidad, tipo, marca y especificación al registrar un cambio de aceite, y \"igual que la última vez\".",
          "**Chequeos con fotos**: hasta 5 fotos por punto en FALLA y en el nuevo **ATENCIÓN**; se ven en el historial y en el álbum.",
          "**Carga parcial**: con el nivel del medidor antes y después, una carga parcial también da consumo, estimado y con su rango; al llegar el próximo tanque lleno se ajusta a lo medido.",
          "**Promedio de consumo más justo**: ahora es kilómetros totales entre combustible total, así un tanque corto no pesa lo mismo que uno largo. Tu promedio puede moverse un poco respecto a la 2.1.",
          "**Viajes**: grábalos con \"Iniciar viaje\" y mira la velocidad en vivo en el tablero de Inicio (distancia, tiempo, media y máxima). Cada viaje guarda su ruta, sus números y sus notas, y ajusta el odómetro estimado.",
          "**Viajes automáticos**: en Android, con el permiso de ubicación \"todo el tiempo\", la app detecta cuando empiezas a manejar y graba el viaje sola. Tiene una guía para los teléfonos Xiaomi.",
          "**Garaje con fotos**: portadas, cuadrícula o lista, con la foto de cada carro; ordénalos a tu gusto y fija uno arriba. El orden se guarda también en la nube.",
          "**Arranque animado**: la aguja del ícono sube a 100 al abrir la app.",
          "**Novedades y versiones**: en *Más* ves la versión que tienes, buscas la última y lees lo nuevo de cada una. Al actualizar, la app te enseña lo nuevo una sola vez.",
          "**Enviar comentario**: reporta un problema o manda una idea desde *Más*, con captura si quieres. Funciona sin cuenta y sin conexión (se envía cuando vuelva).",
          "**Lo que me ha costado**: en Cifras, cuánto te ha costado cada carro desde que lo tienes (compra, mods, mantenimiento, combustible, pista y lo demás) y por kilómetro; también en el reporte PDF y el CSV."
        ]
      }
    ]
  },
  {
    "version": "2.1.3",
    "name": null,
    "date": "2026-09-29",
    "unreleased": false,
    "intro": [],
    "sections": [
      {
        "title": null,
        "intro": [],
        "items": [
          "**Fotos en Android**: agregar la foto de un carro nuevo (o de un chequeo, un servicio) ya no falla con un error raro. Si una foto no se puede guardar, la app lo dice claro y te deja reintentar con la misma foto.",
          "**Cuenta disponible en el APK**: \"Iniciar sesión\" funciona desde el APK que se descarga de GitHub (hasta la 2.1.2 ese APK salía sin la conexión a la nube).",
          "**Cambiar la contraseña**: el enlace de \"¿Olvidaste la contraseña?\" ahora abre Car Guy (antes abría otra app) y ahí mismo escribes la contraseña nueva.",
          "**Cuentas propias de Car Guy**: solo entra una cuenta creada en Car Guy. Una cuenta de otra app no sirve aquí aunque el correo y la contraseña sean correctos.",
          "**Mensajes claros**: ningún mensaje de error muestra detalles técnicos. La pantalla de Cuenta dice la versión de la app.",
          "Preparación para la 2.2: los cambios que haga una versión más nueva se guardan para cuando actualices, en vez de mezclarse mal.",
          "El APK de cada versión se publica también como `car-guy.apk`, con un enlace que siempre apunta a la última."
        ]
      }
    ]
  },
  {
    "version": "2.1.2",
    "name": null,
    "date": "2026-09-29",
    "unreleased": false,
    "intro": [],
    "sections": [
      {
        "title": null,
        "intro": [],
        "items": [
          "Pista: el **trazado** del evento (completo, corto…); las mejores vueltas se comparan en el mismo trazado, y la ficha pública lo muestra.",
          "Pista: **gomas por sesión** — marca en cada sesión las gomas que salieron y cada una suma un ciclo de calor por salida (la marca del día sigue en el evento).",
          "Garaje compartido: los miembros ven los tipos de servicio y las listas de chequeo propias del dueño que usa ese carro.",
          "Por dentro: Expo al día (57.0.26), menos avisos de seguridad en dependencias (de 18 a 3) y sin los avisos de los gráficos en la web."
        ]
      }
    ]
  },
  {
    "version": "2.1.1",
    "name": null,
    "date": "2026-09-29",
    "unreleased": false,
    "intro": [],
    "sections": [
      {
        "title": null,
        "intro": [],
        "items": [
          "La búsqueda ignora acentos y mayúsculas: \"optimo\" encuentra \"Óptimo\", en el historial y en los códigos OBD.",
          "En un carro compartido, los miembros ven los nombres de las pistas y categorías de mods del dueño."
        ]
      }
    ]
  },
  {
    "version": "2.1.0",
    "name": "Hachi-Gō",
    "date": "2026-09-29",
    "unreleased": false,
    "intro": [
      "El garaje deja de ser una lista de carros y se vuelve la historia de cada uno: las fotos de siempre con su fecha, el build con lo que costó, la ficha para el taller, los días de pista y un link para enseñarlo. Se actualiza **encima** de la 2.0.0: los datos se quedan y la base de datos se migra sola al abrir."
    ],
    "sections": [
      {
        "title": "Look JDM",
        "intro": [],
        "items": [
          "Tablero con tacómetro, luces testigo, odómetro LCD y badges (motor, DRIFT, SWAP, EX).",
          "Pestaña **Garaje** con portada, apodo en katakana, estado (activo, proyecto, guardado, vendido) y la historia de los que ya se fueron.",
          "Encabezados en mayúscula, secciones con eyebrow, carbono y señales de peligro donde tocan."
        ]
      },
      {
        "title": "Álbum y memoria",
        "intro": [],
        "items": [
          "Importar fotos viejas con su fecha real (EXIF), sin duplicados, en una línea de tiempo por año.",
          "Hitos (compra, swap, choque, primer track day), \"cómo estaba el carro ese día\", favoritas.",
          "Miniaturas de 400 px y copia de 1600 px; 300 MB de fotos en la nube por cuenta, con medidor."
        ]
      },
      {
        "title": "Build",
        "intro": [],
        "items": [
          "Mods con categoría, marca, costos en RD$ (o en USD con la tasa), instalador y fotos antes/después; STOCK → ACTUAL calculado de los mods; wishlist que se convierte en mod; inventario de piezas, aros y gomas (DOT, ciclos de calor).",
          "La ficha técnica se comparte como imagen."
        ]
      },
      {
        "title": "DIY",
        "intro": [],
        "items": [
          "Ficha de servicio con presets por plataforma (AE85, S13, Civic, DS3…), VIN por vPIC, y \"verificado por mí\" en cada dato. Siempre: *verifica con tu manual*.",
          "Guía de fluidos con tus fotos, que sale en el chequeo; códigos OBD en español; contactos con llamada y WhatsApp."
        ]
      },
      {
        "title": "Pista",
        "intro": [],
        "items": [
          "Eventos (track day, drift, drag, autocross, junte) y sesiones con setup completo: presiones frío → caliente por goma (traseras en rojo si suben más de 8 psi), alineación, altura, suspensión, frenos, ángulo y LSD, tiempos en m:ss.mmm.",
          "**Copiar a la sesión siguiente** y el aviso \"Cambiaste desde la sesión 1: TI/TD 40 → 42\".",
          "Gomas usadas (ciclos), goma quemada, medida de pastillas con recordatorio \"Pastillas (pista)\".",
          "Resumen del día para compartir como imagen o texto; días de pista y su gasto en Cifras."
        ]
      },
      {
        "title": "Compartir",
        "intro": [],
        "items": [
          "**Ficha pública por link** (`car-guy.vercel.app/c/…`) con vista previa en WhatsApp: tú eliges qué se ve (historia, mods, mantenimiento, pista, km, costos, placa, VIN) y hasta 24 fotos. Se desactiva cuando quieras.",
          "**Libro del carro** en PDF: portada, ficha, historia, mods, mantenimiento, documentos, pista y hasta 60 fotos.",
          "**Garaje compartido**: invita a alguien a un carro como editor o solo lectura; el dueño cambia roles o lo quita."
        ]
      },
      {
        "title": "Arreglos",
        "intro": [],
        "items": [
          "Documentos en PDF (antes solo fotos).",
          "Cifras: el eje empieza en 0; en la computadora la app es una columna centrada.",
          "Borrar un carro ahora borra también lo que anotaste de gomas y pastillas en pista."
        ]
      },
      {
        "title": "Antes de publicar (2026-09-29)",
        "intro": [],
        "items": [
          "Probado en un teléfono real (Redmi Note 10 Pro, Android 13) **instalando encima de la versión anterior con datos reales**: el garaje quedó intacto y la base de datos se migró sola.",
          "En el teléfono: libro PDF, ficha para el taller, pista (presiones, copiar sesión, resumen como imagen y texto), menú de un mod, contactos, invitación por link y adjuntar PDF.",
          "En la web y en la nube: la ficha pública por link (con vista previa en WhatsApp confirmada), el garaje compartido entre dos cuentas (invitar, editar, solo lectura, quitar) y la sincronización.",
          "La web de producción no tenía configurada la nube desde que se mudó de proyecto: ya la tiene, así que la cuenta y la sincronización funcionan también en `car-guy.vercel.app`.",
          "Una falla de seguridad en el garaje compartido (cualquier cuenta podía invitarse a un carro ajeno) se encontró y se cerró antes de que existieran cuentas reales."
        ]
      }
    ]
  },
  {
    "version": "2.0.0",
    "name": "Car Guy",
    "date": "2026-09-25",
    "unreleased": false,
    "intro": [
      "Primera versión de Car Guy para Android. Se probó en un teléfono real (Redmi Note 10 Pro, Android 13), en la web y con la sincronización entre dos dispositivos. Lo que esas pruebas encontraron ya viene arreglado en esta versión — ver *Antes de publicar* al final.",
      "Tu Combustible RD se convirtió en **Car Guy**. El combustible sigue completo, pero ya no es el centro: ahora está al lado del aceite que toca a los 5,000 km y del marbete que vence en enero.",
      "**Car Guy se instala aparte de Tu Combustible RD**, no encima. El paquete Android es nuevo (`com.xaviel.carguy`), así que la app vieja sigue con sus datos hasta que la desinstales. Tus datos entran por *Más → Restaurar o importar respaldo*, que lee el respaldo JSON de Tu Combustible RD — y lo seguirá leyendo siempre."
    ],
    "sections": [
      {
        "title": "Nombre e identidad",
        "intro": [],
        "items": [
          "Car Guy: nombre, ícono, splash, tema oscuro por defecto y claro para el sol del mediodía.",
          "Todo el texto de la app vive en un solo archivo (`lib/i18n/es.ts`), en español dominicano.",
          "En la web, los avisos ya no usan el diálogo del navegador: son parte de la app."
        ]
      },
      {
        "title": "Garaje",
        "intro": [],
        "items": [
          "Uno o varios vehículos, cada uno con perfil, odómetro, foto y datos de compra.",
          "Carro, jeepeta, camioneta, motor, camión, guagua.",
          "Vehículos archivados: salen del camino sin perder su historial."
        ]
      },
      {
        "title": "Mantenimiento e historial",
        "intro": [],
        "items": [
          "Servicios, reparaciones y mejoras con fecha, odómetro, costo de piezas y mano de obra, taller, garantía y piezas usadas.",
          "Gastos: seguro, marbete, peaje, lavado y lo demás.",
          "Tareas pendientes, documentos (seguro, marbete, matrícula, facturas) con fotos.",
          "**Un solo historial** por vehículo: cargas, mantenimientos, chequeos y gastos en la misma línea de tiempo, con filtros y búsqueda."
        ]
      },
      {
        "title": "Chequeos y recordatorios",
        "intro": [],
        "items": [
          "Listas diarias, semanales y mensuales. Una falla se convierte en tarea, no en un recuerdo.",
          "Recordatorios por fecha, por kilometraje o lo que llegue primero, con fecha estimada según tus km/día reales.",
          "Marbete, seguro y licencia con las reglas dominicanas (ventana del marbete incluida).",
          "Notificaciones locales, con hora configurable."
        ]
      },
      {
        "title": "Combustible",
        "intro": [],
        "items": [
          "Cargas con fecha, odómetro, estación, tanque lleno o parcial.",
          "Llena dos de tres — volumen, precio por unidad, total — y el tercero se calcula.",
          "Consumo real *brim-to-brim* entre tanques llenos. Si se te olvidó registrar una carga, lo marcas y la cuenta empieza de nuevo en vez de mentir.",
          "Precios MICM de referencia, editables. GNV en m³."
        ]
      },
      {
        "title": "Cifras",
        "intro": [],
        "items": [
          "Costo por km, gasto por categoría y mes a mes, distancia por mes, costo total de propiedad y lo que viene.",
          "Reporte PDF y exportación CSV del historial y de las cargas."
        ]
      },
      {
        "title": "Cuenta y nube (opcional)",
        "intro": [],
        "items": [
          "La app funciona igual sin cuenta. Con cuenta, si cambias de teléfono, tus datos te siguen.",
          "Sincronización local-first: gana la edición más reciente, los borrados viajan como tal y no resucitan, y las fotos van a almacenamiento privado.",
          "Sincroniza al abrir la app, unos segundos después de escribir, al volver la conexión y cuando lo pidas. Si falla, lo dice y lo vuelve a intentar solo — nada se pierde, todo está en el teléfono.",
          "**Cerrar sesión no borra nada de este teléfono.** \"Borrar datos en la nube\" borra del servidor y cierra la sesión; lo local se queda."
        ]
      },
      {
        "title": "Datos",
        "intro": [],
        "items": [
          "Todo en SQLite (`carguy.db`) en el teléfono; en la web, en OPFS del navegador.",
          "Respaldo JSON v2 con todas las tablas. Restaurar combina por id y gana el cambio más reciente: restaurar un respaldo viejo no deshace lo que hiciste después.",
          "Importa respaldos v1 de Tu Combustible RD sin duplicar, aunque los importes dos veces."
        ]
      },
      {
        "title": "Antes de publicar (2026-09-25)",
        "intro": [
          "Pruebas en el teléfono, dos navegadores haciendo de dispositivos y tres testers recorriendo la app:"
        ],
        "items": [
          "**Sincronización:** en un teléfono nuevo no bajaba nada; ahora sí, con fotos. Ya no se pierden filas en tablas grandes ni cambios hechos mientras sincroniza, y un choque entre dos teléfonos lo gana el cambio más reciente. «Borrar datos locales» y «Borrar datos en la nube» funcionan de verdad.",
          "**Consumo:** después de una carga parcial ya no aparece un falso «posibles fugas»; la cuenta es la misma que en Inicio.",
          "**Números:** «1,500» se lee como mil quinientos (antes era 1.5), igual que en un recibo dominicano.",
          "**Teléfono:** el teclado ya no tapa el campo que escribes; «Atrás» desde una notificación vuelve al Inicio en vez de cerrar la app; el PDF se comparte con un nombre claro.",
          "**Datos:** no se aceptan fechas futuras en cargas y lecturas; el marbete registrado dos veces no salta un año; los valores inválidos se rechazan con un mensaje en vez de guardarse como 0.",
          "**Pantallas:** un registro borrado muestra un aviso en vez de una pantalla en blanco; la búsqueda del Historial encuentra «gasolina»; los números de Cifras ya no se cortan."
        ]
      }
    ]
  },
  {
    "version": "1.1.1",
    "name": "Tu Combustible RD",
    "date": "2026-09-17",
    "unreleased": false,
    "intro": [
      "Arreglo del compartir del respaldo en Android. Ver las notas de esa versión."
    ],
    "sections": []
  },
  {
    "version": "1.1.0",
    "name": "Tu Combustible RD",
    "date": "2026-08-19",
    "unreleased": false,
    "intro": [
      "Última versión de Tu Combustible RD antes de Car Guy."
    ],
    "sections": []
  }
];
